ecommerce/cart/urls.py
from django.urls import path
from .import views
app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_details,name='cart_details'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('eshop.urls')),
    path('search_app/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/eshop/urls.py
from django.urls import path
from .import views
app_name = 'eshop'
urlpatterns = [

    path('',views.allprodcat,name='allprodcat'),
    path('<slug:c_slug>/',views.allprodcat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.prodetail,name='prodcatdetail'),
]

ecommerce/search_app/urls.py
from django.urls import path
from .import views

app_name = 'search_app'

urlpatterns =[
    path('',views.search_result,name='search_result'),
]

ecommerce/cart/models.py
from django.db import models
from eshop.models import product

class Cart(models.Model):
    cart_id = models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

        def __str__(self):
            return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product = models.ForeignKey(product,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerce/eshop/models.py
from django.db import models
from django.urls import reverse


class category (models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def get_url(self):
        return reverse('eshop:products_by_category',args=[self.slug,])

    def __str__(self):
        return '{}'.format(self.name)

class product (models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product',blank=True)
    stock = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    available = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('eshop:prodcatdetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def __str__(self):
        return '{}'.format(self.name)

ecommerce/search_app/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from eshop.models import product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

def _cart_id (request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart
def add_cart (request,product_id):
    products = product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item = CartItem.objects.get(product=products,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=products,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_details')

def cart_details (request,total=0,counter=0,cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove (request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    products = get_object_or_404(product,id=product_id)
    cart_item = CartItem.objects.get(product=products,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_details')

def full_remove (request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product1 = get_object_or_404(product, id=product_id)
    cart_item = CartItem.objects.get(product=product1,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_details')

ecommerce/eshop/views.py
from django.shortcuts import render, get_object_or_404
from .models import category,product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

def allprodcat(request,c_slug=None):
    c_page = None
    products_list = None
    if c_slug!=None:
        c_page = get_object_or_404(category,slug=c_slug)
        products_list = product.objects.all().filter(category=c_page,available=True)
    else:
        products_list = product.objects.all().filter(available=True)
    paginator = Paginator(products_list,6)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except(EmptyPage,InvalidPage):
        products = Paginator.page(paginator.num_pages)
    return render(request,"category.html",{'category':c_page,'products':products})

def prodetail(request,c_slug,product_slug,):
    try:
        product1 = product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product1':product1})

ecommerce/search_app/views.py
from django.shortcuts import render
from eshop.models import product
from django.db.models import Q

def search_result (request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.rtl.min.css" integrity="sha384-dc2NSrAXbAkjrdm9IYrX10fQq9SDG6Vjz7nQVKdKcJl3pC+k37e7qJR5MVSCS+wR" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block Title %}{% endblock%}</title>
</head>
<body>
<div>
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
</body>
</html>

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
This is the Cart Page.proceed to review your items and place your order.
{% endblock %}
{% block title %}
    Cart-Hill Top Pvt Ltd
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class=" text-center my_title ">
            Your Shopping Cart is Empty
        </h1>
        <br>
        <p class="text-center">
            Please Click <a href="{% url 'eshop:allprodcat' %}"> Here </a> to continue shopping.
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title ">
            Your shopping Cart
        </h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead ">
            <tr>
                <th colspan="5">
                    Your items
                </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get.absolute_url"><img src="{{cart_item.product.image.url}}" alt="" style="width:100px;height:100px" class="float-left rounded custom_image "></a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    SKU :  {{cart_item.product.id}}
                    <br>
                    Price : $ {{cart_item.product.price}}
                    <br>
                    QTY : {{cart_item.quantity}} x $ {{cart_item}}
                </td>
                <td>
                    $ {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                     <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus" ></i></a>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                {% else %}
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
                </td>
            </tr>
               {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table">
        <thead class="my_custom_thead">
        <tr>
            <th>
                CheckOut
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                Please review your shopping cart before proceeding with your order payment.
            </td>
        </tr>
        <tr>
            <td class="text-left">
                Your Total is :<strong> {{ total }} </strong>
            </td>
        </tr>
        </tbody>
    </table>

<div class="mx-auto">
    <a href="{% url 'eshop:allprodcat'%}" class="btn btn-secondary btn-block my_custom_button "> Continue Shopping </a>
</div>
</div>
{% endif %}
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% if category %}
    {{ category.description|truncatewords:155}}
{% else %}
    Welcome to Hill Top E-shop,where you can find your different items..
{% endif %}
{% endblock %}
{% block title %}
{% if category %}
    {{ category.name}} - Hill Top E-shop
{% else %}
    Let's explore the wide range of collections. - Hill Top E-shop
{% endif %}
{% endblock %}
{% block content %}
    {% if category %}
<div>
    <div class="row my_row_class">
        <div class="mx-auto">
        <p><a href="{% url 'eshop:allprodcat' %}">Our product collection</a></p>
    </div>
        </div>
</div>
    {% endif %}
<div class="mx-auto">
    {% if category %}
        <img class="my_image" src="{{ category.image.url }}" alt="{{category.name}}" width="1550px" height="400px;">
</div>
<br>
<div>
        <h1 class="text-center my_title">{{category.name}}</h1>
        <p class="text-justify">{{category.description}}</p>
</div>
    {% else %}
<div>
        <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt="Our products" width="1550px;" >
</div>
<br>
<div>
        <h1 class="text-center my_title">Our collections</h1>
        <p class="text-justify">Online shopping is a form of electronic commerce which allows consumers to directly buy goods or services from a seller over the Internet using a web browser or a mobile app. Consumers find a product of interest by visiting the website of the retailer directly or by searching among alternative vendors using a shopping search engine, which displays the same product's availability and pricing at different e-retailers. As of 2020, customers can shop online using a range of different computers and devices, including desktop computers, laptops, tablet computers and smartphones.</p>
</div>
    {% endif %}
<br>
<div class="container">
    <div class="row mx-auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  xol-lg-4" >
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" width="250px" height="250px;"></a>
                <div>
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}" >{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

ecommerce/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer p ">
    <p class="text-center">&copy; Hill top Tech pvt ltd.All rights Reserved</p>
</div>

ecommerce/templates/header.html
{% load static %}
<header>
<center>
    <a href="{% url 'eshop:allprodcat' %}"></a><img src="{% static 'img/logo.png' %}" alt="logimage" width="130px" height="80px;">
</center>
</header>

ecommerce/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'eshop' in request.path %}Active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'eshop:allprodcat' %}">All products</a></li>
               {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
              {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_details' %}"><i class="fa fa-shopping-cart"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" role="search" action="{% url 'search_app:search_result' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{ product.description|truncatewords:155}}
{% endblock %}
{% block title %}
{% if category %}
    {{ product.name}} - Hill Top E-shop
{% endif %}
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
    <div class="mx-auto">
    <p><a href="{% url 'eshop:allprodcat' %}">HOME</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}}</p>
    </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12-col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem;">
            <img src="{{product1.image.url}}" alt="{{product1.name}}" width="220px" height="190px;">
        </div>
    </div>
</div>
<div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
        <h1 class="my_prod_title">{{product1.name}}</h1>
        <p>${{product1.price}}</p>
        <p class="text-justify my_prod_text"> Product Description </p>
        <p>{{product1.description}}</p>
        {% if product.stock <= 0 %}
        <p class="text-justify my_prod_text"><b>Out Of Stock</b></p>
        {% else%}
        <a class="btn btn-secondary" href="{% url 'cart:add_cart' product1.id %}">Add To Cart</a>
        {% endif %}
        </div>
    </div>
</div>
</div>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    We have  variety of products.
{% endblock %}
{% block title %}
    search
{% endblock %}
{% block content %}
<div>
    <P class="text-center my_search_text ">you have searched for :<b>"{{query}}"</b></P>
</div>
<div class="container">
    <div class="row mx-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4  xol-lg-4" >
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}" width="250px" height="250px;"></a>
                <div>
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text" >0 results found </p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}